[package]
name = "ch02_basic_component"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
leptos = { version = "0.8.12", features = ["csr"] }
log = "0.4.28"